name: savdo_uz
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.18.1

  # --- Firebase Paketlari ---
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.0

  # Rasmlarni optimallashtirish va keshlash uchun
  cached_network_image: ^3.3.1

  # QR-kod yaratish uchun
  qr_flutter: ^4.1.0

  # Qurilmadan rasm tanlash uchun
  image_picker: ^1.1.2

  # Yuzni aniqlash va tanish uchun
  camera: ^0.11.0+1
  google_mlkit_face_detection: ^0.11.0
  
  # ---- YUZNI TANISH UCHUN YANGI KUTUBXONALAR ----
  image: ^4.2.0 # Rasmlar bilan chuqurroq ishlash uchun
  tflite_flutter: ^0.10.4 # TensorFlow Lite modelini ishlatish uchun
  # -----------------------------------------------


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Dasturga model faylini tanitish
  assets:
    - assets/ml/