name: savdo_uz
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.0
  cached_network_image: ^3.3.1
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  camera: ^0.11.0+1
  google_mlkit_face_detection: ^0.11.0
  image: ^4.2.0
  tflite_flutter_plus: ^0.0.1 # <--- TUZATILGAN QATOR (VERSİYA PASAYTİRİLDİ)
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/ml/