// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASmOHc3vnGYdlE5D0leWw5iYAIf457MgU',
    appId: '1:280839047582:web:45a8792b4f94ec5b5bae8f',
    messagingSenderId: '280839047582',
    projectId: 'savdo-uz-app',
    authDomain: 'savdo-uz-app.firebaseapp.com',
    storageBucket: 'savdo-uz-app.firebasestorage.app',
    measurementId: 'G-VS5BH3VVS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd90wTsXmBsqj-eFjWt4aK5X3mtXi3ojE',
    appId: '1:280839047582:android:886f1fa403ce9bf65bae8f',
    messagingSenderId: '280839047582',
    projectId: 'savdo-uz-app',
    storageBucket: 'savdo-uz-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASmOHc3vnGYdlE5D0leWw5iYAIf457MgU',
    appId: '1:280839047582:web:91d60496154c391e5bae8f',
    messagingSenderId: '280839047582',
    projectId: 'savdo-uz-app',
    authDomain: 'savdo-uz-app.firebaseapp.com',
    storageBucket: 'savdo-uz-app.firebasestorage.app',
    measurementId: 'G-N10RL7E0L1',
  );

}